---
- name: restart nginx
  supervisorctl:
    name: nginx
    state: restarted

- name: validate nginx configuration
  command: nginx -t -c {{ nginx_config_dir }}/nginx.conf
  changed_when: False

- name: reload nginx configuration
  command: nginx -s reload -c {{ nginx_config_dir }}/nginx.conf
